# Generated by Django 2.2 on 2019-06-26 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='gpu_frequency_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='display_port_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='dvi_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='gpu_frequency',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='hdmi_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='official_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='power_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.MBPowerSchemas'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='usb_c_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='vga_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
