# Generated by Django 2.2 on 2019-06-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0003_auto_20190626_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocard',
            name='ram_frequency',
        ),
        migrations.AddField(
            model_name='videocard',
            name='ram_frequency_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocard',
            name='ram_frequency_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocard',
            name='ram_speed_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocard',
            name='ram_speed_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
