# Generated by Django 2.2 on 2019-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0006_auto_20190628_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='val_avg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='val_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
