# Generated by Django 2.2 on 2019-06-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0007_auto_20190628_1930'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mark',
            name='mark_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='testsoftdict',
            name='test_soft_name_mode_version_uniq',
        ),
        migrations.RemoveField(
            model_name='testsoftdict',
            name='version',
        ),
        migrations.AddField(
            model_name='mark',
            name='test_soft_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='testsoftdict',
            constraint=models.UniqueConstraint(fields=('name', 'mode'), name='test_soft_name_version_uniq'),
        ),
    ]
