# Generated by Django 2.2 on 2019-06-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0008_auto_20190628_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='ram_bit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.RamBitDict'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='ram_frequency_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='ram_frequency_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='ram_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.RamSizeDicts'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='ram_speed_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='ram_speed_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='ram_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.DDRVersionDict'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='gpu_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='ram_bit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.RamBitDict'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='ram_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.RamSizeDicts'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='ram_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.DDRVersionDict'),
        ),
    ]
