# Generated by Django 2.2 on 2019-06-29 05:04

from django.db import migrations


def fill_nulls(apps, schema_editor):
    """

    :param apps:
    :param schema_editor:
    :return:
    """
    GPU = apps.get_model('django_gii_pcmark', 'GPU')
    DDRVersionDict = apps.get_model('django_gii_pcmark', 'DDRVersionDict')
    RamBitDict = apps.get_model('django_gii_pcmark', 'RamBitDict')
    RamSizeDicts = apps.get_model('django_gii_pcmark', 'RamSizeDicts')

    ddr_version_fake, _ = DDRVersionDict.objects.get_or_create(version='Fake')
    ram_bit_fake, _ = RamBitDict.objects.get_or_create(bit=0)
    ram_size_fake, _ = RamSizeDicts.objects.get_or_create(size=0, dimension='Fake')

    GPU.objects.filter(ram_version=None).update(ram_version=ddr_version_fake)
    GPU.objects.filter(ram_bit=None).update(ram_bit=ram_bit_fake)
    GPU.objects.filter(ram_size=None).update(ram_size=ram_size_fake)


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0009_auto_20190629_0804'),
    ]

    operations = [
            migrations.RunPython(fill_nulls)
    ]
