# Generated by Django 2.2 on 2019-06-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0010_auto_20190629_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='ram_bit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.RamBitDict'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='ram_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.RamSizeDicts'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='ram_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.DDRVersionDict'),
        ),
    ]
