# Generated by Django 2.2 on 2019-06-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0013_auto_20190630_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='official_url',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='sata6_count',
        ),
    ]
