# Generated by Django 2.2 on 2019-06-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0014_auto_20190630_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='official_url',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='model',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='producer',
        ),
    ]
