# Generated by Django 2.2 on 2019-06-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0016_auto_20190630_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='gpu_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='gpu_producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.ProducersDict'),
        ),
    ]
