# Generated by Django 2.2 on 2019-07-05 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0019_auto_20190704_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiAliasingDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Справочник: тест версии AA',
            },
        ),
        migrations.CreateModel(
            name='DXVersionsDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Справочник: тест версии DX',
            },
        ),
        migrations.AddField(
            model_name='mark',
            name='anti_aliasing_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.AntiAliasingDict'),
        ),
        migrations.AddField(
            model_name='mark',
            name='directx_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.DXVersionsDict'),
        ),
    ]
