# Generated by Django 2.2 on 2019-07-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0020_auto_20190705_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('gpu_model', models.CharField(blank=True, max_length=50, null=True)),
                ('overclock_cpu_freq', models.PositiveIntegerField(blank=True, null=True)),
                ('overclock_gpu_core_freq', models.PositiveIntegerField(blank=True, null=True)),
                ('overclock_gpu_ram_freq', models.PositiveIntegerField(blank=True, null=True)),
                ('overclock_ram_freq', models.PositiveIntegerField(blank=True, null=True)),
                ('gpu_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.GPUDriversDict')),
                ('gpu_producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.ProducersDict')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.OSDict')),
                ('screen_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.TestScreenSizeDict')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.System')),
            ],
            options={
                'verbose_name_plural': 'Тесты систем, пачки',
            },
        ),
        migrations.AddField(
            model_name='mark',
            name='test_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.TestPack'),
        ),
    ]
