# Generated by Django 2.2 on 2019-07-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0022_auto_20190710_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='gpu_model',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='gpu_producer',
        ),
        migrations.RemoveField(
            model_name='testpack',
            name='gpu_model',
        ),
        migrations.RemoveField(
            model_name='testpack',
            name='gpu_producer',
        ),
    ]
