# Generated by Django 2.2 on 2019-07-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0024_auto_20190710_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
