# Generated by Django 2.2 on 2019-07-12 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0026_auto_20190711_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='screen_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.TestScreenSizeDict'),
        ),
    ]
