# Generated by Django 2.2 on 2019-07-13 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0027_mark_screen_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.System'),
        ),
    ]
