# Generated by Django 2.2 on 2019-07-13 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0030_auto_20190713_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='gpu_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.GPUDriversDict'),
        ),
        migrations.AddField(
            model_name='mark',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.OSDict'),
        ),
        migrations.AddField(
            model_name='mark',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
