# Generated by Django 2.2 on 2019-07-13 05:40

from django.db import migrations


def move_test_to_test_pack(apps, schema):
    """

    :param apps:
    :param schema:
    :return:
    """
    Mark = apps.get_model('django_gii_pcmark', 'Mark')

    for mark in Mark.objects.all():
        if not mark.test_pack:
            continue
        mark.url = mark.test_pack.url
        mark.os = mark.test_pack.os
        mark.gpu_driver = mark.test_pack.gpu_driver
        mark.screen_size = mark.test_pack.screen_size
        mark.save()


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0031_auto_20190713_0840'),
    ]

    operations = [
        migrations.RunPython(move_test_to_test_pack)
    ]
