# Generated by Django 2.2 on 2019-07-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0032_auto_20190713_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='url',
            field=models.URLField(),
        ),
    ]
