# Generated by Django 2.2 on 2019-07-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0033_auto_20190713_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='produce_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpufan',
            name='produce_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdd',
            name='produce_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='produce_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='produce_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='produce_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssd',
            name='produce_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='produce_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocard',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videocard',
            name='produce_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocard',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.ProducersDict'),
        ),
    ]
