# Generated by Django 2.2 on 2019-07-13 13:25

from django.db import migrations


def migrate_data(apps, schema):
    """

    :param apps:
    :param schema:
    :return:
    """
    VideoCard = apps.get_model('django_gii_pcmark', 'VideoCard')

    for vc in VideoCard.objects.all():
        vc.producer = vc.gpu.producer
        vc.model = vc.gpu.model
        vc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0034_auto_20190713_1624'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
