# Generated by Django 2.2 on 2019-07-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0035_auto_20190713_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocard',
            name='gpu',
        ),
        migrations.AlterField(
            model_name='videocard',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gii_pcmark.ProducersDict'),
        ),
        migrations.DeleteModel(
            name='GPU',
        ),
    ]
