# Generated by Django 2.2 on 2019-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gii_pcmark', '0036_auto_20190713_1630'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testsoftdict',
            name='test_soft_name_version_uniq',
        ),
        migrations.AddField(
            model_name='mark',
            name='overclock_cpu_freq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='overclock_gpu_core_freq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='overclock_gpu_ram_freq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='overclock_ram_freq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testsoftdict',
            name='dimension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
